on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kuberegpoc.azurecr.io
        username: ${{ secrets.acr_kuberegpoc_username }}
        password: ${{ secrets.acr_kuberegpoc_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kuberegpoc.azurecr.io/kbnpoc:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kuberegpoc.azurecr.io/kbnpoc:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kbnpoc_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kbn-pocbdf7 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kbn-pocbdf7`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kbn-pocbdf7
        container-registry-url: kuberegpoc.azurecr.io
        container-registry-username: ${{ secrets.acr_kuberegpoc_username }}
        container-registry-password: ${{ secrets.acr_kuberegpoc_password }}
        secret-name: kbnpocdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kbn-pocbdf7
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          kuberegpoc.azurecr.io/kbnpoc:${{ github.sha }}
        imagepullsecrets: |
          kbnpocdockerauth
